/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author Pc
 */
public class game extends javax.swing.JFrame {

    /**
     * Creates new form game
     */
    public game() {
        initComponents();
        go();
        lbl_name.setText(String.valueOf(emp.name).toString());
    }
    int firstnumber,secondnumber,counter=0,countercorrect=0;
    double resultnumber,results;
    
private void go(){
    Random r=new Random();
   firstnumber=r.nextInt(100);
   secondnumber=r.nextInt(100);
   lbl_firstnumber.setText(Integer.toString(firstnumber));
   lbl_secondnumber.setText(Integer.toString(secondnumber));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbl_totalgames = new javax.swing.JLabel();
        lbl_secondnumber = new javax.swing.JLabel();
        cb_islem = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_wronggames = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_firstnumber = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_correctgames = new javax.swing.JLabel();
        txt_resultnumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/outline_logout_black_24dp.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(680, 30, 100, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel3.setText("SCOR PANE");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(560, 670, 220, 30);

        lbl_totalgames.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jPanel2.add(lbl_totalgames);
        lbl_totalgames.setBounds(560, 720, 190, 30);

        lbl_secondnumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_secondnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_secondnumber.setOpaque(true);
        jPanel2.add(lbl_secondnumber);
        lbl_secondnumber.setBounds(270, 300, 310, 60);

        cb_islem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cb_islem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEÇ", "+", "-", "*", "/", " " }));
        cb_islem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cb_islem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_islemActionPerformed(evt);
            }
        });
        jPanel2.add(cb_islem);
        cb_islem.setBounds(380, 240, 100, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setText("CORRECT ANSWER:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(370, 760, 240, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("NAME:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 30, 90, 29);

        lbl_wronggames.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jPanel2.add(lbl_wronggames);
        lbl_wronggames.setBounds(600, 790, 150, 20);

        lbl_name.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jPanel2.add(lbl_name);
        lbl_name.setBounds(120, 20, 110, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Check it");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(360, 500, 140, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("=");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(400, 380, 41, 30);

        lbl_firstnumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_firstnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_firstnumber.setOpaque(true);
        jPanel2.add(lbl_firstnumber);
        lbl_firstnumber.setBounds(270, 160, 310, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setText("TOTAL GAMES:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(370, 730, 190, 20);

        lbl_correctgames.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jPanel2.add(lbl_correctgames);
        lbl_correctgames.setBounds(610, 750, 100, 30);

        txt_resultnumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_resultnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_resultnumber);
        txt_resultnumber.setBounds(270, 420, 310, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setText("WRONG ANSWER:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(370, 790, 240, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/mathematics-background-different-numbers-pattern-2476280.jpg"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 0, 810, 860);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_islemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_islemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_islemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try{
        results=Double.parseDouble(txt_resultnumber.getText()); 
     
    int selection=cb_islem.getSelectedIndex();
    counter++;
    if(selection==1){
        resultnumber=firstnumber+secondnumber;
    }
    else if(selection==2){
        resultnumber=firstnumber-secondnumber;
    }
    else if(selection==3){
        resultnumber=firstnumber*secondnumber;
    }
    else if(selection==4){
        resultnumber=firstnumber/secondnumber;
    }
    
    if(resultnumber==results){
        JOptionPane.showMessageDialog(null,"TEBRİKLER!! CEVABINIZ DOĞRU!!");
        go();
        countercorrect++;
        lbl_totalgames.setText(Integer.toString(counter));
        lbl_correctgames.setText(Integer.toString(countercorrect));
    }
    else{
        JOptionPane.showMessageDialog(null,"CEVABINIZ YANLIŞ!! BAŞKA SEFERE!!");
        go();
        lbl_totalgames.setText(Integer.toString(counter));
        lbl_wronggames.setText(Integer.toString(counter-countercorrect));
    }}
     catch(Exception ex){
         
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_islem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_correctgames;
    private javax.swing.JLabel lbl_firstnumber;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_secondnumber;
    private javax.swing.JLabel lbl_totalgames;
    private javax.swing.JLabel lbl_wronggames;
    private javax.swing.JTextField txt_resultnumber;
    // End of variables declaration//GEN-END:variables
}
